# Generated by Django 4.2.8 on 2024-05-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingproduct',
            name='intr_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='intr_rate2',
            field=models.FloatField(null=True),
        ),
    ]
